### ISSUE TITLE
Nesting template/if/include not working

### ISSUE THREAD

**Issue by winkler1** [dciccale/node-htmlprocessor#12]
Hi- love this tool, not sure if using it correctly. I'm doing conditionals with properties to include images--
```
<!-- build:template -->
<% if (WantImages) { %>

    <div style='display:none'><img src='/images/converted/react-native-todo.jpg'/></div>

<% } %>
<!-- /build -->
```

Processing with `./node_modules/htmlprocessor/bin/htmlprocessor index.html -d './index_opts_latest.json' -o build/index.html -r` gives the right output:
```
<div style='display:none'><img src='/images/converted/react-native-todo.jpg'/></div>
```

But: Nesting an include within it:
```
<!-- build:template -->
<% if (WantImages) { %>

    <!-- build:include image_tags.txt -->
    <!-- /build -->

<% } %>
<!-- /build -->
```

Results in un-processed rules in the output
```
<!-- build:template -->
<% if (WantImages) { %>

    <div style='display:none'><img src='/images/converted/react-native-todo.jpg'/></div>

<% } %>
<!-- /build -->
```

Is this expected/correct? Can solve it by calling htmlprocessor again, but was hoping the -r would do it. Thanks.

**Comment by dciccale** [comment]
the recursive option is only for the `include` block type, if true, includes will be recursive like in this example:

`file1.html`
```html```


```

`file2.html`
```html```
<!-- build:include file3.html --->
<!-- /build -->
```

`file3.html` ... ok you get what I mean, first will include `file2.html` and then run again to include `file3.html` (if recursive mode on)

What you are trying to do is not currently not supported and doubt will be, you should try solving it in other way like running htmlprocessor again.
