### ISSUE TITLE
Problems with onload attribute in a block template

### ISSUE THREAD

**Issue by solcre-gr** [dciccale/node-htmlprocessor#15]
I have this code in my index.html to prevent css blocking:

```html
<!-- build:template
        <link rel="stylesheet" href="css/style.css" media="none" onload="if(media != 'all')media = 'all'">
 /build -->
```

But, when i saw the result file, i found this code:

```html
<link rel="stylesheet" href="css/style.css" media="none" onload="&quot;all&quot;!=media&&(media=&quot;all&quot;)">
```

Look is a problem with the slashes character and i can't found a soulution.
I found a 'cheat' using data functionality, to replace the 'all' value, and solve my problem, but i think this is a bug.

**Comment by dciccale** [comment]
i don't see why you have the  block if there is no template code

**Comment by solcre-gr** [comment]
Sorry i put the "modify version"  of my code, this is my original code.

```html
<!-- build:template
        <link rel="stylesheet" href="css/style-<%= version %>.css" media="none" onload="if(media != 'all')media = 'all'">
        /build -->
    /build -->
```

**Comment by dciccale** [comment]
i've tried that and it works. here is the test.

`Gruntfile.js`
```javascript
module.exports = function (grunt) {
  grunt.initConfig({
    processhtml: {
      template: {
        options: {
          data: {
            version: '1.0.0'
          }
        },
        files: [{
          'dist/template.html': ['template.html']
        }]
      }
    }
  });
};
```

`template.html`

```html
<!doctype html>
<html>
  <head>
    <!-- build:template
    <link rel="stylesheet" href="css/style-<%= version %>.css" media="none" onload="if(media != 'all')media = 'all'">
    /build -->
  </head>

  <body></body>
</html>
```

```sh
$ grunt processhtml:template
```

output `dist/template.html`

```html
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="css/style-1.0.0.css" media="none" onload="if(media != 'all')media = 'all'">
  </head>
  <body></body>
</html>
```

**Comment by dciccale** [comment]
post your gruntfile please

**Comment by solcre-gr** [comment]
Hi Denis,

After i tested the code  for hours, i found the problem. And htmlprocessor don't have the responsability.
I found the problem when i use the code with the Grunt task 'htmlmin' with the option minifyJS.

Thanks for your time, now i turn as closed this issue.

Nice to meet you Denis.

:+1:
