### ISSUE TITLE
--list option resulting in TypeError('Unknown encoding: ' + encoding)

### ISSUE THREAD

**Issue by fpalmcrantz** [dciccale/node-htmlprocessor#18]
process-html version: 0.1.10 release
node version: 4.2.0

As title says, I'm seeing an issue when using the --list option. See detailed error trace below:

```javascript
_stream_writable.js:239
    throw new TypeError('Unknown encoding: ' + encoding);
    ^

TypeError: Unknown encoding: encoding
    at WriteStream.setDefaultEncoding (_stream_writable.js:239:11)
    at new WriteStream (fs.js:1830:10)
    at Object.fs.createWriteStream (fs.js:1789:10)
    at HTMLProcessor.processContent (/Users/fredrik/node_modules/gulp-processhtml/node_modules/htmlprocessor/lib/htmlprocessor.js:177:19)
    at DestroyableTransform.processContent [as _transform] (/Users/fredrik/node_modules/gulp-processhtml/index.js:30:33)
```

Seems the problem is the encoding property of the config object passed to createWriteStream. Looking at line #177

``` javascript
177	listFile = fs.createWriteStream(this.options.list, {
178       flags:    "a",
179       encoding: "encoding",
180       mode:    parseInt('744', 8)
181     });
```

I couldn't find and documentation for passing "encoding" as the value for that property. Changing it to e.g utf8 fixes the issue for me. I assumet the value "encoding" does work (or at least has worked) for users of the module so I'm guessing it's a versioning thing (perhaps something's changed with node). Any ideas?

**Comment by dciccale** [comment]
in previous node docs, v12 and lower, there was an option called `encoding`. however `'encoding'`wasn't a valid value anyway, as far as I saw. 

now with value `'utf8'` will work in previous versions of node and newer.

thanks

**Comment by dciccale** [comment]
next release will be published soon

**Comment by rfender** [comment]
What's your timeline on getting this fix into the npm package? I'm running into this issue on Ubuntu.

**Comment by dciccale** [comment]
@rfender now is published
