### ISSUE TITLE
Call to _getMatch not passing in 'line'

### ISSUE THREAD

**Issue by rfender** [dciccale/node-htmlprocessor#20]
The Parser prototype method, _getMatch(), has a signature with one parameter, line, being passed in but in _writeToList(), 'line' is not getting passed in.

`Parser.prototype._writeToList = function (line, filePath) {
    console.log('_writeToList line: ', line);
  var match = this._getMatch(); <== if you pass 'line' in here things work again.
  console.log('match');
  if (match) {
    this.listFile.write(filePath + ':' + match + '\n');
  }
}`

**Comment by dciccale** [comment]
well spotted!

fixed in 1584d3bc8fe81248499a3a89c0b9232422e60826

will deploy a new release

**Comment by dciccale** [comment]
done!

**Comment by rfender** [comment]
You are too good!! Thanks!
