### ISSUE TITLE
--list option is outputting unexpected content

### ISSUE THREAD

**Issue by rfender** [dciccale/node-htmlprocessor#21]
when running `htmlprocessor www/index.html -o dist/index.html --list replacement.list` the replacement.list file has the following output rather than the src attribute value only:

`build:        <link rel="stylesheet" href="vendor/bootstrap/dist/css/bootstrap.css"/>,vendor/bootstrap/dist/css/bootstrap.css`

I would expect the following:

`build:        vendor/bootstrap/dist/css/bootstrap.css`

**Comment by dciccale** [comment]
apparently it is a bug. maybe @cpu999 could check it out.

however i may have broken it in v2 will come back asap

**Comment by rfender** [comment]
@dciccale and @cpu999 , any status on this issue?

**Comment by dciccale** [comment]
this feature was introduced by @cpu999 so I was trying to reach him here but.. I guess I will have to take on this!

will fix it whenever I find some time this week (max weekend) ok?

**Comment by rfender** [comment]
Sounds good! Thanks!

**Comment by dciccale** [comment]
found the issue, will write some tests and do a new release shortly

**Comment by rfender** [comment]
Thanks, @dciccale !
