### ISSUE TITLE
Is it possible to add a query string (cache buster) to the URLs?

### ISSUE THREAD

**Issue by herrernst** [dciccale/node-htmlprocessor#24]
Hi, for forcing browsers to reload JS/CSS assets if the html is rebuilt, I'd like to append a "random" (Math.random() or Date.now() or the like) query string to the URLs, like:
```
<!-- build:js app.min.js -->
<script src="my/lib/path/lib.js"></script>
<script src="my/deep/development/path/script.js"></script>
<!-- /build -->

<!-- changed to -->
<script src="app.min.js?v=12351345"></script>
```
Is that possible somehow? Thanks

**Comment by dciccale** [comment]
is not currently possible, you either do this

```html
<!-- build:js app.min.js?v=123 -->
<script src="my/lib/path/lib.js"></script>
<script src="my/deep/development/path/script.js"></script>
<!-- /build -->

<!-- changed to -->
<script src="app.min.js?v=123"></script>
```

but will require to manually change the version.

or if you are using some server-side rendering engine you could interpolate a Math.random() from the server, something like this:

```html
<!-- build:js app.min.js?v=${randomVersion} -->
<script src="my/lib/path/lib.js"></script>
<script src="my/deep/development/path/script.js"></script>
<!-- /build -->
```

the syntax may change depending on the engine.

--

One other final possibility is writing your own custom block like so:

```custom-block-jsv.js`

```js
module.exports = function (processor) {
  // This will allow to use this <!-- build:jsv[:target] <value> --> syntax
  processor.registerBlockType('jsv', function (content, block, blockLine, blockContent) {
    var title = '<h1>' + block.asset + '</h1>';
    var result = content.replace(blockLine, title);

    return result;
    return content.replace(blockLine, block.indent + '<script src="' + block.asset + '?v=' + Math.random().toString().substr(2, 9) + '"><\/script>');
  });
};
```

```sh
$ htmlprocessor file.html --custom-block-type custom-block-jsv.js
```

and use `build:jsv` like so:

```html
<!-- build:jsv app.min.js -->
<script src="my/lib/path/lib.js"></script>
<script src="my/deep/development/path/script.js"></script>
<!-- /build -->


<!-- changed to -->
<script src="app.min.js?v=646998649"></script>
```

let me know if some of this works for you

**Comment by herrernst** [comment]
Hi,
thank you very much for your detailed help. Possibility 1 is of no use, because I want it generated dynamically. I'm now using possibility 2 and inject something via template processing before.
Possibility 3 looks nice, will try it sometime; but I would also like it for CSS links; do I have to register another custom block ("cssv")? Or can I do it also with attributes like [src] or [href]?
Thanks again!

**Comment by dciccale** [comment]
you would need another "cssv"
