### ISSUE TITLE
missing support for boolean attributes

### ISSUE THREAD

**Issue by diligiant** [dciccale/node-htmlprocessor#25]
A boolean attribute value is set by its presence or absence. Moreover, "true" and "false" are not allowed by the html spec [2.4.2. Boolean attributes](https://www.w3.org/TR/html/infrastructure.html#sec-boolean-attributes).

**Comment by dciccale** [comment]
what exactly is the use case you're trying to address?

**Comment by digitalica** [comment]
i also dont quite get this... An example maybe?

**Comment by dciccale** [comment]
closing the issue.
if you intend to use the [build:<[attr]>[:targets] <value>](https://github.com/dciccale/grunt-processhtml#buildattrtargets-value) block type, for boolean values, it is not intended for that use case, it is only intended to replace or append to an existing attribute of the html tag.

if you want to conditionally do something more complex, based on a boolean you could use the template [build:template[:targets]](https://github.com/dciccale/grunt-processhtml#buildtemplatetargets) block type like so

```
<!-- build:template
<button disabled="<%= myBooleanTemplateVariable %>"></button>
/build -->
```
